apiVersion: v1
kind: Config
clusters:
- name: "dso"
  cluster:
    server: "https://rancher.cyder.com.sg/k8s/clusters/c-ghkll"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrakNDQ\
      TNxZ0F3SUJBZ0lRQ2dGQlFnQUFBVk9GYzJvTGhleW5DREFOQmdrcWhraUc5dzBCQVFzRkFEQS8KT\
      VNRd0lnWURWUVFLRXh0RWFXZHBkR0ZzSUZOcFoyNWhkSFZ5WlNCVWNuVnpkQ0JEYnk0eEZ6QVZCZ\
      05WQkFNVApEa1JUVkNCU2IyOTBJRU5CSUZnek1CNFhEVEUyTURNeE56RTJOREEwTmxvWERUSXhNR\
      E14TnpFMk5EQTBObG93ClNqRUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9URFV4bGRDZHpJR\
      VZ1WTNKNWNIUXhJekFoQmdOVkJBTVQKR2t4bGRDZHpJRVZ1WTNKNWNIUWdRWFYwYUc5eWFYUjVJR\
      md6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBbk5NTThGcmxMa\
      2UzY2wwM2c3Tm9ZekRxMXpVbUdTWGh2YjQxOFhDU0w3ZTRTMEVGCnE2bWVOUWhZN0xFcXhHaUhDN\
      lBqZGVUbTg2ZGljYnA1Z1dBZjE1R2FuL1BRZUdkeHlHa09sWkhQL3VhWjZXQTgKU014K3lrMTNFa\
      VNkUnh0YTY3bnNIamNBSEp5c2U2Y0Y2czVLNjcxQjVUYVl1Y3Y5YlR5V2FOOGpLa0tRRElaMApaO\
      GgvcFpxNFVtRVVFejlsNllLSHk5djZEbGIyaG9uemhUK1hocSt3M0JydmF3MlZGbjNFSzZCbHNwa\
      0VObldBCmE2eEs4eHVRU1hndm9wWlBLaUFsS1FUR2RNRFFNYzJQTVRpVkZycW9NN2hEOGJFZnd6Q\
      i9vbmt4RXowdE52amoKL1BJemFyazVNY1d2eEkwTkhXUVdNNnI2aENtMjFBdkEySDNEa3dJREFRQ\
      UJvNElCZlRDQ0FYa3dFZ1lEVlIwVApBUUgvQkFnd0JnRUIvd0lCQURBT0JnTlZIUThCQWY4RUJBT\
      UNBWVl3ZndZSUt3WUJCUVVIQVFFRWN6QnhNRElHCkNDc0dBUVVGQnpBQmhpWm9kSFJ3T2k4dmFYT\
      nlaeTUwY25WemRHbGtMbTlqYzNBdWFXUmxiblJ5ZFhOMExtTnYKYlRBN0JnZ3JCZ0VGQlFjd0FvW\
      XZhSFIwY0RvdkwyRndjSE11YVdSbGJuUnlkWE4wTG1OdmJTOXliMjkwY3k5awpjM1J5YjI5MFkyR\
      jRNeTV3TjJNd0h3WURWUjBqQkJnd0ZvQVV4S2V4cEhzc2NmcmI0VXVRZGYvRUZXQ0ZpUkF3ClZBW\
      URWUjBnQkUwd1N6QUlCZ1puZ1F3QkFnRXdQd1lMS3dZQkJBR0MzeE1CQVFFd01EQXVCZ2dyQmdFR\
      kJRY0MKQVJZaWFIUjBjRG92TDJOd2N5NXliMjkwTFhneExteGxkSE5sYm1OeWVYQjBMbTl5WnpBO\
      EJnTlZIUjhFTlRBegpNREdnTDZBdGhpdG9kSFJ3T2k4dlkzSnNMbWxrWlc1MGNuVnpkQzVqYjIwd\
      lJGTlVVazlQVkVOQldETkRVa3d1ClkzSnNNQjBHQTFVZERnUVdCQlNvU21wakJIM2R1dWJST2Jlb\
      VJXWHY4Nmpzb1RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUEzVFBYRWZOaldEamRHQlg3Q1ZXK\
      2RsYTVjRWlsYVVjbmU4SWtDSkx4V2g5S0VpazNKSFJSSEdKbwp1TTJWY0dmbDk2UzhUaWhSelp2b\
      3JvZWQ2dGk2V3FFQm10enczV29kYXRnK1Z5T2VwaDRFWXByLzF3WEt0eDgvCndBcEl2SlN3dG1Wa\
      TRNRlU1YU1xclNERTZlYTczTWoydGNNeW81ak1kNmptZVdVSEs4c28vam9XVW9IT1Vnd3UKWDRQb\
      zFRWXorM2RzemtEcU1wNGZrbHhCd1hSc1cxMEtYelBNVForc09QQXZleXhpbmRtamtXOGxHeStRc\
      1JsRwpQZlorRzZaNmg3bWplbTBZK2lXbGtZY1Y0UElXTDFpd0JpOHNhQ2JHUzVqTjJwOE0rWCtRN\
      1VOS0VrUk9iM042CktPcWtxbTU3VEgySDNlREpBa1NuaDYvRE5GdTBRZz09Ci0tLS0tRU5EIENFU\
      lRJRklDQVRFLS0tLS0="
- name: "dso-ip-172-31-5-85"
  cluster:
    server: "https://172.31.5.85:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURRd01qQXhNekEwT1ZvWERUTXlNRE16TURBeE16QTBPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU9tWXJxeDJFTDhLClBEVkxvWW8xT3BrR2NrS3lnQTV5VmwyWXVNU2VtTHVYb1h5NUFVbDQ2Y\
      U4zWEtXVHZtUlRlOFJOYW5yYU9Bd1IKZzlxRkVHa3plVE4rRDNZK3pVNXo4RUppTWRWb0NaRnhOa\
      3g3VnFjQUVYV1dmbmZaeE0vMHk2cTBJOEVIQkdwegpRUiszazMwQXptQmd2ZGs2UmtJQjA3cXFTV\
      1BFMllvamlnMmlTTElHUm5NNC8zb0l0Qm51aXVjMnlqaVkwdnU4ClJCNk9vNmJ3VnViYTU1a2xYO\
      HFaS2diMHBHbmlsTk5ROVIzdXpGRHkrVjVvdC9xTjlkVXJYWDV0SjBvV2tpZkkKRTdwaUtSV1BmR\
      0oyVXFNR3BzR0hCRXF1bXlQZW5iK1l5N0xvNFZFT2NwajdvYXArS2pHQ1lZTFBJaC90amhJMwpIZ\
      jNOUHQ3UUt2RUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSDIvS3k0bk9UT1kvTU5ITkxBTmZOT\
      HY2bVh4SlRIUU5memgKdjFhbkdMTTRTVk1hVmNjNTAzL0JSYkQ3N3lTVFNhWmlTcmtZUlRUcWYwO\
      EhYMitFRFBNbUFMWTVNRXhHRmVSeApCQVNHV09lM2xuR2J0Umg2MTk2OEY1WVNBMHdyNVg4UkwyN\
      1hXbFVhZU1JL0ZaZGpwWkVjSXovaTQ1UlRxODRSCjRhVEppVXU1VEZnQWFVSWhieFNrR0xGMFVEV\
      lpBZ3JJdk0rRXpmbE5OYmRwVVduMUJaL2NPQUxTNVExa1pKV3MKNVhrcnpvZHJ5L0o3VmdvL2NPN\
      XNyMVhWSnFwTEFOeVRZUkxXNkFlVXJ5NStoZHJMUEJtNGR3Q2lQdm1Udk9yUApISTJEU1JZRitkV\
      StTcEZaUHY3UlZUVHg1QitrVUF6bGI1UlhqTWM3ODNzNkJVQVhLM289Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "dso"
  user:
    token: "kubeconfig-u-h6xkb.c-ghkll:rh5wvncj88vfr7br28gkxckrlbhsv52cwfgg6m59tdk8rj6r8p4brr"

contexts:
- name: "dso"
  context:
    user: "dso"
    cluster: "dso"
- name: "dso-ip-172-31-5-85"
  context:
    user: "dso"
    cluster: "dso-ip-172-31-5-85"

current-context: "dso"

